
### Testing
GET http://localhost:8080/test

### Get all headers
GET http://localhost:8080/headers

### Send json
POST http://localhost:8080/someData
Content-Type: application/json

{
  "price": 125.0,
  "info": {
    "date": "2022-01-01"
  }
}

### Test validation
POST http://localhost:8080/validate
Content-Type: application/json

{
  "data": "A1d"
}


### Buy product1
POST http://localhost:8080/purchases/buy/1
Content-Type: application/json

{
  "productId": "1"
}

### Buy product2
POST http://localhost:8080/purchases/buy/2
Content-Type: application/json

{
  "productId": "2"
}

### Get metric
GET http://localhost:8080/calculate-metric

### Get actuator
GET http://localhost:8080/invoke-actuator


