
### Testing
GET http://localhost:8080/test

### Get all headers
GET http://localhost:8080/headers

### Send json
POST http://localhost:8080/someData
Content-Type: application/json

{
  "price": 125.0,
  "info": {
    "date": "2022-01-01"
  }
}

### Test validation
POST http://localhost:8080/validate
Content-Type: application/json

{
  "data": "A1d"
}


### Testing public api
GET http://localhost:8080/public/api

### Testing admin api admin:password -> Basic YWRtaW46cGFzc3dvcmQ=
GET http://localhost:8080/admin/api
Authorization: Basic YWRtaW46cGFzc3dvcmQ=

### Testing support api support:password -> Basic c3VwcG9ydDpwYXNzd29yZA==
GET http://localhost:8080/support/api
Authorization: Basic c3VwcG9ydDpwYXNzd29yZA==