
### Testing
GET http://localhost:8080/test

### Get all headers
GET http://localhost:8080/headers

### Send json
POST http://localhost:8080/someData
Content-Type: application/json

{
  "price": 125.0,
  "info": {
    "date": "2022-01-01"
  }
}

### Test validation
POST http://localhost:8080/validate
Content-Type: application/json

{
  "data": "A1d"
}


### Test DB
POST http://localhost:8080/api/BD
Content-Type: application/json

{
  "name": "Мой список дел",
  "events": [
    {"name": "дело1"},
    {"name": "дело2"},
    {"name": "дело3"}
  ]
}

### Test DB
GET http://localhost:8080/api/BD