
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: dev
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: java_todo